const emojis = [
  { emoji: "😀", tags: ["smile", "happy", "joy", "face"] },
  { emoji: "😂", tags: ["lol", "funny", "haha", "joy", "tears"] },
  { emoji: "🤣", tags: ["rofl", "laughing", "funny", "lmao"] },
  { emoji: "😊", tags: ["smile", "blush", "happy", "cute"] },
  { emoji: "😍", tags: ["love", "heart", "eyes", "crush"] },
  { emoji: "😘", tags: ["kiss", "love", "flirt", "heart"] },
  { emoji: "😎", tags: ["cool", "sunglasses", "chill", "style"] },
  { emoji: "🤔", tags: ["thinking", "hmm", "question", "idea"] },
  { emoji: "😏", tags: ["smirk", "flirt", "sarcasm", "mischief"] },
  { emoji: "🥲", tags: ["nervous", "relieved", "sad", "awkward"] },
  { emoji: "😭", tags: ["cry", "sad", "tears", "emotional"] },
  { emoji: "😡", tags: ["angry", "mad", "annoyed", "rage"] },
  { emoji: "👍", tags: ["like", "yes", "good", "approve"] },
  { emoji: "👎", tags: ["dislike", "no", "bad", "reject"] },
  { emoji: "🙏", tags: ["pray", "please", "thanks", "hope"] },
  { emoji: "👏", tags: ["clap", "applause", "well done", "respect"] },
  { emoji: "🔥", tags: ["fire", "lit", "cool", "hot", "trend"] },
  { emoji: "💯", tags: ["100", "perfect", "true", "keep it real"] },
  { emoji: "🎉", tags: ["party", "celebration", "congrats", "fun"] },
  { emoji: "❤️", tags: ["love", "heart", "romance", "like"] },
  { emoji: "💔", tags: ["broken", "sad", "heartbreak", "pain"] },
  { emoji: "🥰", tags: ["love", "hearts", "cute", "affection"] },
  { emoji: "🤯", tags: ["mind blown", "shocked", "wow", "crazy"] },
  { emoji: "😴", tags: ["sleep", "tired", "zzz", "rest"] },
  { emoji: "🤮", tags: ["sick", "vomit", "disgusting", "eww"] },
  { emoji: "🤡", tags: ["clown", "funny", "fool", "troll"] },
  { emoji: "💀", tags: ["dead", "skull", "funny", "rip"] },
  { emoji: "🤌", tags: ["italian", "perfect", "hand", "gesture"] },
  { emoji: "✌️", tags: ["peace", "victory", "cool", "two"] },
  { emoji: "🤝", tags: ["handshake", "deal", "agreement", "team"] },
  { emoji: "👀", tags: ["eyes", "look", "watching", "staring"] },
  { emoji: "🍕", tags: ["pizza", "food", "meal", "snack"] },
  { emoji: "☕", tags: ["coffee", "drink", "tea", "morning"] },
  { emoji: "🍔", tags: ["burger", "food", "meal", "snack"] },
  { emoji: "🌸", tags: ["flower", "nature", "cute", "spring"] },
  { emoji: "🌞", tags: ["sun", "morning", "day", "bright"] },
  { emoji: "🌙", tags: ["moon", "night", "sleep", "dark"] },
  { emoji: "⭐", tags: ["star", "favorite", "shine", "night"] },
  { emoji: "⚡", tags: ["lightning", "fast", "zap", "power"] },
];

export default emojis;
